title:            Shannon's Blog
description:      Technical creativity and interesting finds
logo:             SH-logo-final.png
disqus_shortname: shannonholgatesblog
#Comment out url when working locally to resolve base urls correctly
#url:              http://www.shannonholgate.com

# Owner/author information
owner:
  name:           Shannon Holgate
  avatar:         portrait-200-200.jpg
  email:          sholgate1305@gmail.com
  # Social networking links used in footer. Update and remove as you like.
  twitter:        sholgate13
  facebook:
  github:         ShannonHolgate
  stackexchange:
  linkedin:       shannonholgate
  instagram:
  flickr:
  tumblr:
  # For Google Authorship https://plus.google.com/authorship
  google_plus:    https://plus.google.com/110511679166205111076

# Analytics and webmaster tools stuff goes here
google_analytics: UA-40540308-2
google_verify:
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Links to include in top navigation
# For external links add external: true
links:
  - title: Latest
    url: /
  - title: Development
    url: /softdev
  - title: Hadoop
    url: /hadoop
  - title: Project Katie
    url: /katie
  - title: About
    url: /about

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    Europe/London
future:      true
pygments:    false
markdown:    kramdown

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:categories/:title

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false

  coderay:
    coderay_line_numbers:
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: class

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec"]

flickr:
  cache_dir:       "./_cache/flickr"
  api_key:          959200eb8e173f602d1d3526ccf6fe46
  shared_secret:    a5522f7b70f76a54
  access_token:     72157648954077137-4f14ea8a3bb8d5fe
  access_secret:    35b52db82016fb22
